spring:
  profiles:
    active: dev # Configure environment information.
  main:
    allow-circular-references: true # Configure automatic resolution of circular dependencies.
    banner-mode: off
  datasource: # Configure database connection information.
    druid:
      driver-class-name: ${easy.datasource.driver-class-name}
      url: jdbc:mysql://${easy.datasource.host}:${easy.datasource.port}/${easy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${easy.datasource.username}
      password: ${easy.datasource.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Set Spring MVC's path matching strategy to be consistent with Swagger's path matching strategy.
  redis:
    host: ${easy.redis.host}
    port: ${easy.redis.port}
    database: ${easy.redis.database}
    password: ${easy.redis.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # Enable mapping of underscores to camel case in column names.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
    banner: false
  mapper-locations: classpath:mapper/*.xml  # Mapper configuration files.
  type-aliases-package: com.easy.entity



# Configure log levels.
logging:
  level:
    com:
      easy:
        mapper: debug
        service: info
        controller: info

# Configure JWT information.
easy:
  jwt:
    admin-secret-key: easy-take-out # Set the secret key used for JWT signing.
    admin-ttl: 7200000 # Set JWT expiration time.
    admin-token-name: token # Set the name of the token in the request.
    user-secret-key: easy-take-out-user
    user-ttl: 7200000
    user-token-name: authentication

  alioss:
    endpoint: ${easy.alioss.endpoint}
    access-key-id: ${easy.alioss.access-key-id}
    access-key-secret: ${easy.alioss.access-key-secret}
    bucket-name: ${easy.alioss.bucket-name}

  wechat:
    appid: ${easy.wechat.appid}
    secret: ${easy.wechat.secret}
    #wechat Pay merchant information
    mchid: ${sky.wechat.mchid}
    mchSerialNo: ${sky.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiV3Key}
    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}