easy:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: easy_take_out
    username: root
    password: 1234

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 1234

  alioss:
    endpoint: oss-eu-west-1.aliyuncs.com
    access-key-id: LTAI5tKC3BZxVNKkcjdsa9iR
    access-key-secret: 5LoOrtbcgghfwX1bNyF5y1B6M6qLBZ
    bucket-name: sky-take-out-maynooth

  wechat:
    appid: wx0a5df76428140929
    secret: 70f552b0f022f4b7d534ca2d89eca63f
    #wechat Pay merchant information
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: E:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    privateKeyFilePath: E:\pay\apiclient_key.pem
    notifyUrl: http://685470f9.r21.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://685470f9.r21.cpolar.top/notify/refundSuccess