easy:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: easy_take_out
    username: root
    password: 1234

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 1234

  alioss:
    endpoint: oss-eu-west-1.aliyuncs.com
    access-key-id: LTAI5tKC3BZxVNKkcjdsa9iR
    access-key-secret: 5LoOrtbcgghfwX1bNyF5y1B6M6qLBZ
    bucket-name: sky-take-out-maynooth

  wechat:
    appid: wx0a5df76428140929
    secret: 70f552b0f022f4b7d534ca2d89eca63f
    #wechat Pay merchant information
    mchid: 1671088139
    mchSerialNo: 2A22D387A13191D3F70CAA09C30123F884907F95
    apiV3Key: 11111111111111111111111111111111
    weChatPayCertFilePath: D:\WXCertUtil\WXCertUtil\cert\1671088139_20240318_cert\apiclient_cert.pem
    privateKeyFilePath: D:\WXCertUtil\WXCertUtil\cert\1671088139_20240318_cert\apiclient_key.pem
    notifyUrl: https://110461aa.r3.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://110461aa.r3.cpolar.top/notify/refundSuccess